### ISSUE TITLE
CentOS 6.5 SpiderMonkey rpm

### ISSUE THREAD

**Issue by bitsandbytes** [mobdata/build#10]

**Comment by bitsandbytes** [comment]
The default spidermonkey in the EPEL is new enough for our purposes, this ticket is no longer necessary.

**Comment by bitsandbytes** [comment]
According to this guy couchdb is 4x faster on js185 rather than the EPEL's default js17, so making a 1.8.5 rpm is still necessary for deployment, though we can use 1.7 for development purposes.
https://github.com/wendall911/couchdb-rpm
Also, he has a js185 spec file already. https://github.com/wendall911/js185
It's not ideal because it doesn't recognize when the erlang-solutions rpm has been installed, from here: http://packages.erlang-solutions.com/rpm/centos/6/x86_64/esl-erlang-17.5.3-1.x86_64.rpm

**Comment by rruff** [comment]
Got the RPM built using the spec file from above. I kept a list of the tools I had to install on my instance to do the build, so I will make a small wiki page.
